/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Shobu;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testMe() {
        assertEquals(1,1);
    }
}
